[utdallas]
source = notmuch://~/docs/mail
outgoing = smtp+xoauth2://dal558183%40utdallas.edu@smtp-mail.outlook.com:587
outgoing-cred-cmd = oama access dal558183@utdallas.edu
from = "Harrison, Henry" <dal558183@utdallas.edu>
check-mail = 1m
check-mail-cmd = /home/zlare/.local/bin/mail-sync.sh
check-mail-timeout = 120s
query-map = /home/zlare/.config/aerc/query-map
maildir-store = /home/zlare/docs/mail/utdallas
maildir-account-path = utdallas
default = inbox
enable-folders-sort = true
folders-sort = inbox,unread,routed,sent,all
folders-exclude = INBOX,Sent Items
